### ISSUE TITLE
Stateful behaviour in OpenQL leading to strange errors

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#171]
I have had some problem triggering this bug as it sometimes appears and sometimes does not. 
The behaviour is as follows: 
- A valid openQL program (v0.5.1) is written in an ipython notebook. 
- When evaluating the cell sometimes (~50%) everything works as expected 
- Sometimes it gives an error that the classical operations is not allowed. 
- I am not sure what triggers this bug but it makes it impossible to develop and make programs using classical programs. I am however quite sure that it somehow depends on the state of the compiler as a clean restart of the python kernel (not feasible in practical settings) makes the problem goes away only to appear again slightly later. 

```python 
output_dir = os.path.join(os.path.abspath(pq.__path__[0]),'tests', 'openql', 'test_output')
ql.set_option('output_dir', output_dir)

ql.set_option('scheduler', 'ALAP')

nregisters=5

platf = ql.Platform('OpenQL_Platform', cfg_filname)
nqubits = platf.get_qubit_number()
p = ql.Program('Scheduling_test', platf, nqubits, nregisters)

k = ql.Kernel('test_kernel', platf, nqubits, nregisters)

# for i in range(5):
    
rs1 = ql.CReg()
k.classical(rs1, ql.Operation(0))

k.prepz(0)
k.prepz(2)

# rs = ql.CReg()

for i in range(10):
    k.gate('rx180', [0])

for i in range(6):
    k.gate('rx90', [2])
k.gate('wait', [0,2], 0)
k.measure(2)
k.measure(0)
p.add_kernel(k)
p.compile()

```

Output 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-4efde8dad63f> in <module>()
     15 
     16 rs1 = ql.CReg()
---> 17 k.classical(rs1, ql.Operation(0))
     18 
     19 k.prepz(0)

~/GitHubRepos/DiCarloLab_Repositories/OpenQL/openql/openql.py in classical(self, *args)
   1152 
   1153         """
-> 1154         return _openql.Kernel_classical(self, *args)
   1155 
   1156 

TypeError: Out of range operand(s) for 'ldi' !

```

**Comment by jvanstraten** [comment]
To whom it may concern: the entire register allocation code was not only stateful but also dependent on Python's garbage collection logic to free registers; any ql.CReg constructed and remaining in Python's object storage would (continue to) claim exclusive access a control register regardless of the program or even platform being compiled for. So whenever some IPython kernel that happens to be running in the same Python process has a CReg in memory anywhere, no other program can use that CReg, and thus the numbering would be different. Some instructions seem to only be defined for specific registers, so you'd get an error when trying to add an instruction when the OpenQL-allocated register just so happens to be incorrect.

The test Imran wrote for it didn't catch it, because it did `ql.CReg()` outside of the test loop, and (probably) Python would even be smart enough to clean the objects if you'd do the assignment in the loop. But there are no guarantees here.

I ran into it while updating all the tests to check their output against golden versions, and there was non-deterministic behavior all over the place. I just tore out automatic register allocation entirely for now as part of our cleanup efforts, since Hans and I are not sure whether classical registers are even being used by anyone anymore.

**Comment by wvlothuizen** [comment]
I just checked, pycQED currently does not use any creg, so you don't break anything there...
