### ISSUE TITLE
Clarity on use/utility of kernels

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#257]
This thread should be used for a discussion on the use of kernels in OpenQL. I propose this be done in two steps:
1) describing the current thought process behind the use of kernels in OpenQL. I trust that @imranashraf or @jvansomeren can provide some input on this
2) discussion on the merits of the current approach and how this construct should be used in the future

**Comment by jvansomeren** [comment]
Multiple issues here now.
1. doc has been written which should clarify this; please read/review it and then we'll do 2.
2. kernel's are used to create control flow; creating this is different from creating sequential classical gates and is different from creating quantum gates; it doesn't allow scheduling over it, which might soon be a requirement; the control flow that can be created, is limited to some high-level constructs; the internal representation depends on this and so this precludes transforming/optimizing this since the low-level conditional branch primitive to jump to any kernel is missing; and there is more ...
I propose to make a separate issue of 2.
