### ISSUE TITLE
Better way of describing conditional gate execution

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#262]
OpenQL is currently a combination of API calls. Expressing classical construct is very counter intuitive. This can be improved.

**Comment by wvlothuizen** [comment]
Below is a quote of an old post of mine on slack channel '#openql-and-friends' that pertains to this subject:

> As some of you know, I'm working on an OpenQL backend for the new Central Controller. This CC differs from the CClight in that it has no notion of quantum operations and internally has a distributed architecture (with a separate processor per connected instrument). In order to be able to support conditional instructions, we need to be able to relate measurements (currently performed on an UHFQC) to actions (performed on VSM or maybe AWG). Because we have no a priori knowledge of the mapping of qubits on either, we devised an end user programmable (i.e. through the backend) Condition Engine.
> This Condition Engine can do many more things than the implicit conditional gates of the CClight (e.g. support expressions on 2 qubits, and support a concept of state), but these are currently difficult/impossible to express in OpenQL.
> Of course we can (and probably will) support the current conditional gates, but I think it would be a great improvement if the condition could be passed as a parameter (preferably a logic expression).
> We also support program flow conditional on measurement results ("comprehensive feedback"). This can only be expressed by the user in 'classical QASM', which is a bit awkward to support for us because it is very close to the CClight internal instruction set, but much less so to ours. As an example, we support a 'loop' instruction which combines decrementing a register and a conditional branch. As another example, in our instructions measurement results live in a register space different from the classic processor registers (namely in distributed shared memory controlled by the real time part of the processor). I think all of those translations would be easier if the classical part of QASM would be a higher level language.
> All in all I think a discussion on classical logic would be appropriate (maybe that is already going on for libqasm2.0, but I'm not connected to that)

**Comment by wvlothuizen** [comment]
meeting homework:

documentation on the CC can be found in the Central Controller dropbox. If you require access please let me know. Places to have a look are "doc/design/CC", "doc/presentations" and "doc/requirements/CC".

**Comment by wvlothuizen** [comment]
meeting homework:

indeed the instruction set of the CC does not operate at the qubit and quantum gate level like the CC-light, but instead it deals with digital inputs (from a UHFQC) and outputs (to an AWG). Moreover, the architecture is distributed: one sequence processor controls one instrument only, and sequence processors can exchange data (measurements) using Distributed Shared Memory.
The current CC OpenQL backend mostly produces digital output (the seq_out instruction), the translation process from a quantum gate to a digital output happens in the backend (contrary to the CC-light where the ISA performs this), and involves the mapping of qubits to instruments.
The CC "Q1" processor supports classical instructions like add, or, xor, see file "Q1_SEQ Instructionset.xlsx" in dropbox:/doc/design/CC. Additionally, the Distributed Shared Memory fabric supports a programmable feedback data path, see "cc_firmware_implementation-20191203.pdf" section 4.5.3.1 and 4.5.3.1 and also "CC-soft+firm-ware-design.docx" section 2.3

Feel free to ask more questions after reading through the documentation,

**Comment by wvlothuizen** [comment]
Meeting homework:

Feedback requirements are discussed in Sections A.11 and further of dropbox:doc/requirements/CC/QuSurf_CC_UseCases.docx

The feedback implementation of the CC was pointed to above: "Additionally, the Distributed Shared Memory fabric supports a programmable feedback data path, see "cc_firmware_implementation-20191203.pdf" section 4.5.3.1 and 4.5.3.1 and also "CC-soft+firm-ware-design.docx" section 2.3"

**Comment by wvlothuizen** [comment]
Update:

dropbox:doc/requirements/CC/CC_conditionalGates.docx discusses the relation between use cases for conditional gates and the code to implement those on the CC

**Comment by wvlothuizen** [comment]
Some remarks per section...

CC support:
- the input is not necessarily limited to the last and previous measurements. It can choose bits from a 128 bit view of Shared Memory (which is 1024 bits in total). SM can be written by a measurement, or by QEC;
- apart from XOR, also AND and OR are supported;
- implementing complex expressions using multiple rounds through Programmable Logic is not intended. The PL cannot write to Shared Memory, only to the state variable.

OpenQL layers:
- I don't think we should support breaking down complex conditional expressions. The whole idea of the PL is to have a low (and fixed) latency mechanism for conditional gates that can operate on multiple qubits at the same time. Bringing in additional classical operations will make things slow and difficult to schedule. I'd say that if the expression is too complex, compilation should fail. If that happens in practice, we should extend the capabilities of PL.

What's already there:
- the cQASM/libqasm syntax has two problems in my opinion:
  - it 'breaks' the normal gate syntax because the condition is between the gate and the operands, which makes it difficult to read;
  - the "c-" prefix changes the gate name, which seems counterintuitive. It also leaves the question whether "c-x" uses the same gate definition as "x", and makes it impossible to have normal gates start with "c-".
- to me, OpenQASM's syntax "if(creg==int) qop;" is clear and would be extendible to allow more complex expressions.

Conditional expressions:
- I don't think *implicit* notion of last and previous measurements should be added, but that the user should explicitly assign two classical variables;
- the cQASM way to perform a `bitcomplement r0, r1` is counterintuitive to me: it actually assigns a value to r1, while that's not what the user intends, neither is it what will happen on the CC. To me, `{ IF r0 X q0 | IF ~r0 Y q1 }` is way more readable;
- if we redesign the syntax of conditional gates, we should also bear in mind the 'randomized benchmarking' use case, which requires real time selection of a gate from an array of gates (24 Cliffords in this case), based on a classic variable (a random number in this case);
- currently scheduling is done at the kernel level, and classic conditional constructs (FOR, IF, WHILE) operate on kernels. I think this precludes having a classical variable life time beyond a single kernel, which would be a severe limitation.

**Comment by MiguelSMoreira** [comment]
Next step would be to test the implementation by using conditional gates in the lab
