### ISSUE TITLE
Update CC backend to use the RC scheduler

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#400]
Could you please elaborate on this work @jvanstraten ?

**Comment by jvanstraten** [comment]
This is mostly about updating the CC backend to use the RC scheduler, which is hitting all kinds of engineering debt, for instance that the configuration files in use in the lab now do not properly configure the resources (since they weren't used) which we have to deal with somehow now. This is touching on proper validation and desugaring of the JSON configuration file, leading to more work. This is just an example though, there is stuff like this all over the place.

The end goal is easy however; usage of the RC scheduler for CC in practice in the lab, rather than the basic one.

There may or may not be more to be done for fill multi-measurement support (such as changing the cQASM reader to put barriers around bundles, if we decide to do that), but those should probably be separate issues when they come up, so I'll change the title for this one.

**Comment by MiguelSMoreira** [comment]
Modifications tested across SSRO, AllXY and RB experiments successfully in an experimental setup.
Issue can be closed!
